name: OrangeMechanic
version: '${version}'
main: ltd.icecold.orangeengine.OrangeMechanic
api-version: 1.17
authors: [ icecold ]
description: Provide MythicMobs and CitizensNPC support for OrangeEngine
website: https://www.icecold.ltd/
depend:
  - ProtocolLib
  - MythicMobs
  - OrangeEngine
softdepend:
  - Citizens